/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QComboBox *comboBox;
    QLabel *label_4;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QFrame *frame_13;
    QLabel *label_10;
    QFrame *frame_12;
    QLabel *label_16;
    QFrame *frame_11;
    QLabel *label_17;
    QFrame *frame_10;
    QLabel *label_11;
    QFrame *frame_9;
    QLabel *label_18;
    QFrame *frame_8;
    QLabel *label_15;
    QFrame *frame_7;
    QLabel *label_19;
    QFrame *frame_6;
    QLabel *label_21;
    QFrame *frame_5;
    QLabel *label_14;
    QFrame *frame_4;
    QLabel *label_13;
    QFrame *frame_3;
    QLabel *label_12;
    QFrame *frame_2;
    QLabel *label_20;
    QLabel *label_9;
    QFrame *line;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QLabel *label_22;
    QLabel *label_23;
    QComboBox *comboBox_2;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QComboBox *comboBox_3;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QPushButton *pushButton_6;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QMenuBar *menuBar;
    QMenu *menuRhetty_to_Risk;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(761, 670);
        MainWindow->setAutoFillBackground(false);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(450, 410, 121, 32));
        pushButton->setStyleSheet(QStringLiteral(""));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(620, 410, 113, 191));
        QFont font;
        font.setPointSize(40);
        pushButton_2->setFont(font);
        pushButton_2->setStyleSheet(QStringLiteral("color: rgba(255, 17, 31, 191)"));
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(240, 410, 141, 32));
        comboBox = new QComboBox(centralWidget);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(250, 500, 121, 26));
        comboBox->setMaxVisibleItems(1);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(250, 440, 141, 61));
        pushButton_7 = new QPushButton(centralWidget);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(250, 540, 121, 32));
        pushButton_7->setStyleSheet(QStringLiteral(""));
        pushButton_8 = new QPushButton(centralWidget);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(250, 570, 121, 32));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(50, 410, 141, 16));
        QFont font1;
        font1.setPointSize(20);
        label->setFont(font1);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(70, 460, 59, 16));
        label_2->setFont(font1);
        label_2->setStyleSheet(QStringLiteral("color: rgb(58, 255, 69)"));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(70, 520, 59, 16));
        label_3->setFont(font1);
        label_3->setStyleSheet(QStringLiteral("color: rgb(255, 24, 36)"));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(50, 580, 71, 16));
        label_5->setFont(font1);
        label_5->setStyleSheet(QStringLiteral("color: rgb(62, 163, 255)"));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(140, 460, 59, 16));
        label_6->setFont(font1);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(140, 520, 59, 16));
        label_7->setFont(font1);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(140, 580, 59, 16));
        label_8->setFont(font1);
        frame_13 = new QFrame(centralWidget);
        frame_13->setObjectName(QStringLiteral("frame_13"));
        frame_13->setGeometry(QRect(620, 310, 111, 31));
        frame_13->setStyleSheet(QStringLiteral("background-color: rgba(196, 46, 255, 38)"));
        frame_13->setFrameShape(QFrame::StyledPanel);
        frame_13->setFrameShadow(QFrame::Raised);
        label_10 = new QLabel(frame_13);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 10, 61, 16));
        frame_12 = new QFrame(centralWidget);
        frame_12->setObjectName(QStringLiteral("frame_12"));
        frame_12->setGeometry(QRect(620, 150, 111, 31));
        frame_12->setStyleSheet(QStringLiteral("background-color: rgba(196, 46, 255, 38)"));
        frame_12->setFrameShape(QFrame::StyledPanel);
        frame_12->setFrameShadow(QFrame::Raised);
        label_16 = new QLabel(frame_12);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(30, 10, 59, 16));
        frame_11 = new QFrame(centralWidget);
        frame_11->setObjectName(QStringLiteral("frame_11"));
        frame_11->setGeometry(QRect(500, 150, 111, 31));
        frame_11->setStyleSheet(QStringLiteral("background-color: rgba(196, 46, 255, 38)"));
        frame_11->setFrameShape(QFrame::StyledPanel);
        frame_11->setFrameShadow(QFrame::Raised);
        label_17 = new QLabel(frame_11);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(30, 10, 59, 16));
        label_17->raise();
        frame_10 = new QFrame(centralWidget);
        frame_10->setObjectName(QStringLiteral("frame_10"));
        frame_10->setGeometry(QRect(500, 310, 111, 31));
        frame_10->setStyleSheet(QStringLiteral("background-color: rgba(196, 46, 255, 38)"));
        frame_10->setFrameShape(QFrame::StyledPanel);
        frame_10->setFrameShadow(QFrame::Raised);
        label_11 = new QLabel(frame_10);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 10, 59, 16));
        frame_9 = new QFrame(centralWidget);
        frame_9->setObjectName(QStringLiteral("frame_9"));
        frame_9->setGeometry(QRect(380, 150, 111, 31));
        frame_9->setStyleSheet(QLatin1String("background-color: rgba(46, 255, 35, 38)\n"
"\n"
""));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Raised);
        label_18 = new QLabel(frame_9);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(30, 10, 59, 16));
        frame_8 = new QFrame(centralWidget);
        frame_8->setObjectName(QStringLiteral("frame_8"));
        frame_8->setGeometry(QRect(20, 310, 111, 31));
        frame_8->setStyleSheet(QStringLiteral("background-color: rgba(51, 151, 255, 38)"));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        label_15 = new QLabel(frame_8);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(30, 10, 59, 16));
        frame_7 = new QFrame(centralWidget);
        frame_7->setObjectName(QStringLiteral("frame_7"));
        frame_7->setGeometry(QRect(260, 150, 111, 31));
        frame_7->setStyleSheet(QLatin1String("background-color: rgba(46, 255, 35, 38)\n"
"\n"
""));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        label_19 = new QLabel(frame_7);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(30, 10, 59, 16));
        frame_6 = new QFrame(centralWidget);
        frame_6->setObjectName(QStringLiteral("frame_6"));
        frame_6->setGeometry(QRect(20, 150, 111, 31));
        frame_6->setStyleSheet(QStringLiteral("background-color: rgba(51, 151, 255, 38)"));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        label_21 = new QLabel(frame_6);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 10, 91, 20));
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(140, 310, 111, 31));
        frame_5->setStyleSheet(QStringLiteral("background-color: rgba(51, 151, 255, 38)"));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        label_14 = new QLabel(frame_5);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 10, 59, 16));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(260, 310, 111, 31));
        frame_4->setStyleSheet(QStringLiteral("background-color: rgba(46, 255, 35, 38)"));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_13 = new QLabel(frame_4);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 10, 59, 16));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(380, 310, 111, 31));
        frame_3->setStyleSheet(QStringLiteral("background-color: rgba(46, 255, 35, 38)"));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        label_12 = new QLabel(frame_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 10, 59, 16));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(140, 150, 111, 31));
        frame_2->setStyleSheet(QStringLiteral("background-color: rgba(51, 151, 255, 38)"));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_20 = new QLabel(frame_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(30, 10, 59, 16));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(280, 10, 141, 31));
        QFont font2;
        font2.setPointSize(25);
        label_9->setFont(font2);
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 379, 761, 16));
        line->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0)"));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label_33 = new QLabel(centralWidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(30, 190, 91, 16));
        QFont font3;
        font3.setPointSize(8);
        label_33->setFont(font3);
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(30, 350, 91, 16));
        label_34->setFont(font3);
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(150, 190, 91, 16));
        label_35->setFont(font3);
        label_36 = new QLabel(centralWidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(150, 350, 91, 16));
        label_36->setFont(font3);
        label_37 = new QLabel(centralWidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(270, 190, 91, 16));
        label_37->setFont(font3);
        label_38 = new QLabel(centralWidget);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(270, 350, 91, 16));
        label_38->setFont(font3);
        label_39 = new QLabel(centralWidget);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(390, 190, 91, 16));
        label_39->setFont(font3);
        label_40 = new QLabel(centralWidget);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(390, 350, 91, 16));
        label_40->setFont(font3);
        label_41 = new QLabel(centralWidget);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(510, 190, 91, 16));
        label_41->setFont(font3);
        label_42 = new QLabel(centralWidget);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(510, 350, 91, 16));
        label_42->setFont(font3);
        label_43 = new QLabel(centralWidget);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(630, 190, 91, 16));
        label_43->setFont(font3);
        label_44 = new QLabel(centralWidget);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(630, 350, 91, 16));
        label_44->setFont(font3);
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(245, 430, 251, 61));
        QFont font4;
        font4.setPointSize(38);
        pushButton_4->setFont(font4);
        pushButton_5 = new QPushButton(centralWidget);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(560, 10, 111, 41));
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(420, 10, 91, 31));
        label_22->setFont(font2);
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(460, 440, 121, 61));
        comboBox_2 = new QComboBox(centralWidget);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(450, 510, 121, 26));
        comboBox_2->setMaxVisibleItems(1);
        pushButton_9 = new QPushButton(centralWidget);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(450, 580, 121, 32));
        pushButton_9->setStyleSheet(QStringLiteral(""));
        pushButton_10 = new QPushButton(centralWidget);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(450, 550, 121, 32));
        pushButton_10->setStyleSheet(QStringLiteral(""));
        comboBox_3 = new QComboBox(centralWidget);
        comboBox_3->setObjectName(QStringLiteral("comboBox_3"));
        comboBox_3->setGeometry(QRect(450, 490, 121, 26));
        comboBox_3->setMaxVisibleItems(1);
        pushButton_11 = new QPushButton(centralWidget);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(450, 530, 121, 32));
        pushButton_11->setStyleSheet(QStringLiteral(""));
        pushButton_12 = new QPushButton(centralWidget);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(450, 560, 121, 32));
        pushButton_12->setStyleSheet(QStringLiteral(""));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(630, 210, 90, 90));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(390, 50, 90, 90));
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(150, 210, 90, 90));
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(390, 210, 90, 90));
        label_28 = new QLabel(centralWidget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(30, 210, 90, 90));
        label_29 = new QLabel(centralWidget);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(270, 50, 90, 90));
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(630, 50, 90, 90));
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(510, 210, 90, 90));
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(150, 50, 90, 90));
        label_45 = new QLabel(centralWidget);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(270, 210, 90, 90));
        label_46 = new QLabel(centralWidget);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(30, 50, 90, 90));
        label_47 = new QLabel(centralWidget);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(510, 50, 90, 90));
        pushButton_6 = new QPushButton(centralWidget);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(70, 10, 113, 41));
        pushButton_6->setStyleSheet(QStringLiteral(""));
        label_48 = new QLabel(centralWidget);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(300, 20, 161, 121));
        label_48->setFont(font1);
        label_48->setStyleSheet(QStringLiteral("color: rgb(230, 46, 36)"));
        label_49 = new QLabel(centralWidget);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(-2, 5, 761, 611));
        label_49->setStyleSheet(QStringLiteral("background-color: rgb(0,0,0)"));
        label_50 = new QLabel(centralWidget);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(180, 120, 400, 142));
        label_51 = new QLabel(centralWidget);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(320, 300, 100, 46));
        label_52 = new QLabel(centralWidget);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(240, 410, 151, 191));
        label_53 = new QLabel(centralWidget);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(0, 385, 761, 281));
        label_53->setStyleSheet(QStringLiteral("background-color: rgb(255, 250, 227)"));
        MainWindow->setCentralWidget(centralWidget);
        label_53->raise();
        label_49->raise();
        pushButton_4->raise();
        frame_10->raise();
        frame_13->raise();
        frame_8->raise();
        frame_11->raise();
        frame_3->raise();
        frame_12->raise();
        frame_9->raise();
        frame_6->raise();
        frame_5->raise();
        frame_7->raise();
        frame_4->raise();
        pushButton->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        comboBox->raise();
        label_4->raise();
        pushButton_7->raise();
        pushButton_8->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        frame_2->raise();
        label_9->raise();
        line->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        pushButton_5->raise();
        label_22->raise();
        label_23->raise();
        comboBox_2->raise();
        pushButton_9->raise();
        pushButton_10->raise();
        comboBox_3->raise();
        pushButton_11->raise();
        pushButton_12->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        label_29->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_45->raise();
        label_46->raise();
        label_47->raise();
        pushButton_6->raise();
        label_48->raise();
        label_50->raise();
        label_51->raise();
        label_52->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 761, 22));
        menuRhetty_to_Risk = new QMenu(menuBar);
        menuRhetty_to_Risk->setObjectName(QStringLiteral("menuRhetty_to_Risk"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuRhetty_to_Risk->menuAction());

        retranslateUi(MainWindow);
        QObject::connect(pushButton_5, SIGNAL(clicked()), MainWindow, SLOT(close()));

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Attack!", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "End \n"
"Turn", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "Allocate Students", 0));
        label_4->setText(QString());
        pushButton_7->setText(QApplication::translate("MainWindow", "Place Students", 0));
        pushButton_8->setText(QApplication::translate("MainWindow", "Cancel", 0));
        label->setText(QApplication::translate("MainWindow", "Student Count", 0));
        label_2->setText(QApplication::translate("MainWindow", "Dan:", 0));
        label_3->setText(QApplication::translate("MainWindow", "Cole:", 0));
        label_5->setText(QApplication::translate("MainWindow", "Powell:", 0));
        label_6->setText(QApplication::translate("MainWindow", "5", 0));
        label_7->setText(QApplication::translate("MainWindow", "5", 0));
        label_8->setText(QApplication::translate("MainWindow", "5", 0));
        label_10->setText(QApplication::translate("MainWindow", "Bookstore", 0));
        label_16->setText(QApplication::translate("MainWindow", "Kilachand", 0));
        label_17->setText(QApplication::translate("MainWindow", "Bay State", 0));
        label_11->setText(QApplication::translate("MainWindow", "Questrom", 0));
        label_18->setText(QApplication::translate("MainWindow", "CAS", 0));
        label_15->setText(QApplication::translate("MainWindow", "Fitrec", 0));
        label_19->setText(QApplication::translate("MainWindow", "GSU", 0));
        label_21->setText(QApplication::translate("MainWindow", "West Campus", 0));
        label_14->setText(QApplication::translate("MainWindow", "CGS", 0));
        label_13->setText(QApplication::translate("MainWindow", "Warren", 0));
        label_12->setText(QApplication::translate("MainWindow", "Comm", 0));
        label_20->setText(QApplication::translate("MainWindow", "Stuvi", 0));
        label_9->setText(QApplication::translate("MainWindow", "Player Turn: ", 0));
        label_33->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_34->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_35->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_36->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_37->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_38->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_39->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_40->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_41->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_42->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_43->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        label_44->setText(QApplication::translate("MainWindow", "Student Count:", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "Start Game!", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "End Game", 0));
        label_22->setText(QApplication::translate("MainWindow", "Dan", 0));
        label_23->setText(QString());
        pushButton_9->setText(QApplication::translate("MainWindow", "Cancel", 0));
        pushButton_10->setText(QApplication::translate("MainWindow", "Confirm", 0));
        pushButton_11->setText(QApplication::translate("MainWindow", "Confirm", 0));
        pushButton_12->setText(QApplication::translate("MainWindow", "Cancel", 0));
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QString());
        label_28->setText(QString());
        label_29->setText(QString());
        label_30->setText(QString());
        label_31->setText(QString());
        label_32->setText(QString());
        label_45->setText(QString());
        label_46->setText(QString());
        label_47->setText(QString());
        pushButton_6->setText(QApplication::translate("MainWindow", "New Game", 0));
        label_48->setText(QApplication::translate("MainWindow", "Congratulations!", 0));
        label_49->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_50->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_51->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_52->setText(QString());
        label_53->setText(QString());
        menuRhetty_to_Risk->setTitle(QApplication::translate("MainWindow", "Rhetty to Risk", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
